### PR TITLE
OSM trademark message and fix typo

### PR DESCRIPTION
**Pull request by aerostitch**
Fixes: https://github.com/navit-gps/navit/issues/849

### CODE REVIEW

**Comment by mvglasow** [comment]
Where would the trademark disclaimer appear? In the animation? Or somewhere else?

**Comment by aerostitch** [comment]
Yes, it will look like:
Screenshot from 2019-09-04 14-24-51
 (Based on the way I undferstand the OpenStreetmap trademark policy it has to be the closest possible to the trademark itself)

**Comment by mvglasow** [comment]
Looks good to me, except that there is still a typo (should be “disclaimer”, not “discalimer”). Although, as I understand the comment by @simonpoole in navit-gps/navit#849:

> I would suggest adding disclaimers to the footer

it would be sufficient to place the disclaimer in the footer, not necessarily in the banner itself.

**Comment by aerostitch** [comment]
Thanks for the review.
I fixed the disclaimer typo.

If you read the policy it states:
> The notice should appear near the first use of any OSM mark. One notice is enough if you display multiple marks, provided the notice refers to all of them.

Which made me think that the disclaimer should be closer than the footer.
@pgrandin @jkoan opinion on this?

**Comment by jkoan** [comment]
Sory guys, i missed this one

**Pull request merged**
